### ISSUE TITLE
Error while processing route: home Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by officeguy** [aws-samples/aws-mobilehub-ember#3]
Hi @mlabieniec ,

I've tried this as per the blog, twice, and am getting this error on the /home route.
```
Uncaught (in promise) WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"http://localhost:4200/assets/failed.png","error":{"name":"invalid-response-for-caching","message":"The fetched response could not be cached due to an invalid response code."}}'
    at http://localhost:4200/workbox-sw.prod.v2.1.0.js:160:1358
    at Generator.throw (<anonymous>)
    at step (http://localhost:4200/workbox-sw.prod.v2.1.0.js:83:30)
    at http://localhost:4200/workbox-sw.prod.v2.1.0.js:96:13
```
and then
```
Error while processing route: home Unexpected token o in JSON at position 1 SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Module.callback (http://localhost:4200/assets/ember-mobilehub-tester.js:14:28)
    at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:66242:20)
    at Class.resolveOther (http://localhost:4200/assets/vendor.js:65960:32)
    at Class.superWrapper [as resolveOther] (http://localhost:4200/assets/vendor.js:53562:22)
    at Class.resolve (http://localhost:4200/assets/vendor.js:17906:35)
    at resolve (http://localhost:4200/assets/vendor.js:15303:36)
    at Registry.resolve (http://localhost:4200/assets/vendor.js:14764:21)
```
and
```
ember.debug.js:19840 SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Module.callback (note.js:10)
    at Module.exports (loader.js:106)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:391)
    at Class.resolveOther (index.js:109)
    at Class.superWrapper [as resolveOther] (ember.debug.js:42856)
    at Class.resolve (ember.debug.js:7200)
    at resolve (ember.debug.js:4597)
    at Registry.resolve (ember.debug.js:4058)
```

authentication seems fine for the /home route, and it displays the session expiration, and all jwt id and access fields.

any ideas?
ref:
```
ember-cli: 2.13.1
node: 8.9.3
os: darwin x64
```

thanks.. marty

**Comment by officeguy** [comment]
resolution via https://github.com/aws-samples/aws-mobilehub-ember/pull/4
